# Generated by Django 5.0.3 on 2024-03-19 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('history', models.TextField(help_text='Enter a brief description of the pet', max_length=500)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='petInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this pet', primary_key=True, serialize=False)),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.pet')),
            ],
        ),
    ]
