# Generated by Django 5.0.3 on 2024-03-19 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_petinstance_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinstance',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.pet'),
        ),
    ]
