# Generated by Django 5.0.3 on 2024-03-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_petinstance_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='size',
            new_name='pet_breed',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='history',
            new_name='pet_history',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='pet_name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='pet_size',
        ),
    ]
