# Generated by Django 5.0.3 on 2024-03-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_size_pet_pet_breed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_history',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_size',
            new_name='size',
        ),
    ]
